[build]
  builder = "nixpacks"
  buildCommand = "npm run build"
  installCommand = "npm install"
  startCommand = "npm run preview"
  
[deploy]
  startCommand = "npm run preview"
  
[build.environment]
  NODE_ENV = "production"
  
[build.prebuild]
  prebuild_commands = [
    "corepack enable",
    "corepack prepare pnpm@latest --activate"
  ]

[healthcheck]
  enabled = true
  interval = 10
  timeout = 5
  retries = 3
  startPeriod = 30
  path = "/"
  port = 3000
  
  
[checks]
  type = "readiness"
  interval = "10s"
  timeout = "5s"
  retries = 3
